apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi

