apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: monitoring
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: LoadBalancer

