apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless-svc
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    app: prometheus
  clusterIP: None
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
